language: java
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
script: mvn package
after_success:
- travis/deploy.sh
env:
  global:
  - secure: vGW9Nrvl5c7KLemcTqITu+G3s9x2cNhHhz3bjTq6zH3CKRE7k/m84TCcAxdeHgOXkDh4yaAhwx9tkTSS7kcOWnJooyDZ2YrOm9vBjttSHcOO6UHbcUo4/joD36332b4C2nK+K/vfV23StBRqq4qPHOjpfBVxBOINPAGBm3oGsv9TuDlGu1HNF1fsaYbSOQvsZy5ijJpEsOs0S5XEpEhXD09ikz0sRY4jDARNbQLvYzCTs/+2QRi7d35W/wTmRfPoWXtc3U77+K0adjVD6U5jBuLF7IKrUEgxaxOVWaaUaRfN+M1mN6HIrau3McK3sKcC4ZJBzDOURuWiQtOd7ZMbFt/lsVejtSXxt2XWINmhevpELcqDUgdE9Pu937ejFloHBzlOQfyI+PbgS7KjCNeOsqveQG9haKDP9O6AA7WP/t5mEqz0O+krFGwfd0tHPbE8tpx+W6Hi8F3iimp16jahUJVeQmO+N8V62cArSBEXx/MeAvbkuE6sWlvrvuj+LqkVf5/S8RiIPzoS9kxM/ioJ3y/YHWmlrLRXkeFExftdusRE+d1pHb6DpaHR3MXaaWyVQPmhR7aqwzi0mXMxLNtGzV70QcgWgsU8ZFbTZmWt5GXKNrbX7QMluhhrogTk980eN58mqOZCDteF6L9OI1YCh0PSlirV9VRT2v27QKeJacM=
  - secure: JXtilzmdkpo4d8Zc89iz3hCTBXDDZ/6jFqgk6dKjT+pSlyqwfIKBEc0opezqnf/KZCdaNW+cWU26ngoBLwNd36ldshOpS+rfOUHC0pT0lnpP50+jazlUWap1Si1z/M325+rhdOdPGUvZOTRGkeZi3lYBdNLlWcTZEjaB/Cpi/v2UH24H1w9OHnxZPui54eIwQARpOJ80oWGDffizEy6pC0rOgSTEOQVxmjaOdP3PcD/rnsRNiFjem7tZ2QGtfl4I6NB8X5UVYL3/vNNOZab6iSc9hy5hD8IKYMCTzq0vvZ/jQAFAUyUibtyvyKHexWD5QQ4vKcaxrBkIIbcvu3Wdcewgcxs8Ou7xa8eSYKl9CimPEPx+L3rEG3vdvfnn9fCZW7JPjCJx1c+AlrWSouxIB0f2gfBNP4g0QZIMnQuWNb+1+l1rygC6Wz+hFu3v+rXwLTlm3RXIr26AVc8FGOjOwnLH+U32VeQQAe/2r0ROGy9X+dIoA35FJhimtz/XJdUWsRw3P3f1fmSq/bFdNZhYmRtTQGBRXlNqEaRrhtJdmnUf6ywWDH4YRRbRFkORDkH9Lkjx8MoM5N0qGuoJm8Ay0Fi3/8YH1LsbZgI++jsXsNsB9FGHUYdDfH0ebUGsEeX+9q4Bl5XgZ2Lokxs3N6/Ib61DXnBhXM90WrTrwkvLbRM=
